services:
  - type: web
    name: retailza-api
    runtime: python
    plan: free
    region: singapore # Closest low-latency region to India
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.2
      - key: APP_NAME
        value: Retailza
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: "true"
      - key: SECRET_KEY
        value: retailza_super_secret_jwt_key_kirana_saas_2026_production
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "10080"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "30"
      - key: OTP_EXPIRE_MINUTES
        value: "5"
      - key: DEBUG_MOCK_OTP
        value: "true"
      - key: MOCK_OTP_CODE
        value: "123456"
      - key: SMS_PROVIDER
        value: fast2sms
      - key: FAST2SMS_API_KEY
        value: hXIfLmtDixvHZy1VnkFojqzBs0Ju3EKe6MAG9QgcCTlr7ap4wdpG2QYqSEsaCzPojAei06hb34fNgKdl
      - key: RAZORPAY_KEY_ID
        value: rzp_test_TWXn6r1HPxwz0r
      - key: RAZORPAY_KEY_SECRET
        value: 6u35s2LHnOuWVlBWF94HP1by
      - key: SUBSCRIPTION_AMOUNT
        value: "49.00"
